name: Sync Fork and Modify Content

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/sync_and_merge.yaml'
  schedule:
    - cron: '0 16 * * *'  # Runs at 16:00 UTC every day, which is 00:00 UTC+8

jobs:
  sync-and-modify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures history is fetched

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'

      # Step 3: Add the upstream repository
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git

      # Step 4: Fetch the latest changes from the upstream repository
      - name: Fetch Upstream
        run: |
          git fetch upstream
          git checkout master

      # Step 5: Merge changes from upstream, favoring their changes in conflicts
      - name: Merge Upstream Changes
        run: git merge upstream/master --strategy-option theirs

      # Step 6: Modify files
      - name: Modify Files Excluding Markdown Files
        run: |
          find rule/Clash -type f ! -name "*.md" -exec sed -i '/IP-ASN/d' {} \;
          # 用Surge中的WeChat替换Clash中WeChat文件
          cat rule/Surge/WeChat/WeChat.list | sed '/^#/d' > temp.yaml
          sed -i '/IP-ASN/d' temp.yaml
          echo "# Total count: $(wc -l < temp.yaml)" > rule/Clash/WeChat/WeChat.yaml
          echo "payload:" >> rule/Clash/WeChat/WeChat.yaml
          cat temp.yaml | sed -r "s/(.*)/  - \1/g" >> rule/Clash/WeChat/WeChat.yaml
          rm -rf temp.yaml
          # 修正rewrite/Loon/AdvertisingLite/AdvertisingLite.plugin中误杀的规则
          sed -i -r 's#\^https\?:\\/\\/mlol\\\.qt\\\.qq\\\.com\\/go\\/recommend - reject#^https?:\\/\\/mlol\\\.qt\\\.qq\\\.com\\/go\\/recommend\\/(?!v2\\/platactivity\.*) - reject#g' rewrite/Loon/AdvertisingLite/AdvertisingLite.plugin
          # 为rewrite/Loon/AdvertisingLite/AdvertisingLite.plugin添加规则
          # sed -i '49 a ^https:\\/\\/booking\\.bestwehotel\\.com\\/proxy\\/trip-hotel-banner\\/activity\\/getActivityInfo - reject-200' rewrite/Loon/AdvertisingLite/AdvertisingLite.plugin
          # sed -i '$ s/$/,booking.bestwehotel.com/' rewrite/Loon/AdvertisingLite/AdvertisingLite.plugin
          # 为rule/Surge/ChinaMax/ChinaMax_All_No_Resolve.list加上GEOIP,CN
          # echo -n "GEOIP,CN" >> rule/Surge/ChinaMax/ChinaMax_All_No_Resolve.list
          
      # Step 7: Check for changes and commit if any
      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync from upstream and modify files"
            git push origin master
          else
            echo "No changes to commit"
          fi
